baseurl = "http://www.example.com"
canonifyurls = true
defaultcontentlanguage = "pt-br"
disqusShortname = "yourdiscussshortname"
languagecode = "pt-br"
paginate = 20
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "b2"
theme = "hugo-coder"
title = "Rosario Marrazzo"
[languages.en]
languagename = "English"
[[languages.en.menu.main]]
name = "About"
url = "about/"
weight = 1
[[languages.en.menu.main]]
name = "Blog"
url = "posts/"
weight = 2
[[languages.en.menu.main]]
name = "Projects"
url = "projects/"
weight = 3
[[languages.en.menu.main]]
name = "Contact me"
url = "contact/"
weight = 5
[languages.pt-br]
languagename = "Italiano"
title = "Rosario Marrazzo"
[[languages.pt-br.menu.main]]
name = "Sobre"
url = "about/"
weight = 1
[[languages.pt-br.menu.main]]
name = "Blog"
url = "posts/"
weight = 2
[[languages.pt-br.menu.main]]
name = "Projetos"
url = "projects/"
weight = 3
[[languages.pt-br.menu.main]]
name = "Contato"
url = "contact/"
weight = 5
[languages.pt-br.params]
author = "Rosario Marrazzo"
description = "Sítio pessoal de João Ninguém"
footercontent = "Coloque algum texto aqui."
info = "Digital Transformation Student"
keywords = "blog,desenvolvedor,pessoal"
since = 9
[params]
author = "Rosario Marrazzo"
avatarurl = "images/avatar.jpg"
colorscheme = "auto"
commit = "https://github.com/luizdepra/hugo-coder/tree/"
custom_css = []
custom_js = []
dateformat = "January 2, 2006"
description = "John Doe's personal website"
footercontent = "Enter a text here."
hideCopyright = false
hideCredits = false
hideFooter = false
info = "Digital Transformation Student"
keywords = "blog,developer,personal"
maxSeeAlsoItems = 5
rtl = false
since = 2019
[params.fathomAnalytics]
serverURL = "analytics.example.com"
siteID = "ABCDE"
[[params.social]]
icon = "fab fa-github"
name = "Github"
url = "https://github.com/johndoe/"
weight = 1
[[params.social]]
icon = "fab fa-gitlab"
name = "Gitlab"
url = "https://gitlab.com/johndoe/"
weight = 2
[[params.social]]
icon = "fab fa-twitter"
name = "Twitter"
url = "https://twitter.com/johndoe/"
weight = 3
[[params.social]]
icon = "fab fa-linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/johndoe/"
weight = 4
[[params.social]]
icon = "fab fa-medium"
name = "Medium"
url = "https://medium.com/@johndoe"
weight = 5
[[params.social]]
icon = "fas fa-rss"
name = "RSS"
rel = "alternate"
type = "application/rss+xml"
url = "https://myhugosite.com/index.xml"
weight = 6
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
